/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LanguageButton: typeof import('./src/components/Header/Partials/LanguageButton.vue')['default']
    PSidebarProvider: typeof import('./src/components/Sidebar/Partials/PSidebarProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VFooter: typeof import('./src/components/common/VFooter.vue')['default']
    VHeader: typeof import('./src/components/Header/VHeader.vue')['default']
    VHeaderDashboard: typeof import('./src/components/Header/VHeaderDashboard.vue')['default']
    VLogin: typeof import('./src/components/Auth/VLogin.vue')['default']
    VRegister: typeof import('./src/components/Auth/VRegister.vue')['default']
    VSidebar: typeof import('./src/components/Sidebar/VSidebar.vue')['default']
  }
}
